name: Heroku deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
#      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "demo-aej"
#          heroku_email: "kucingapes@gmail.com"
#          justlogin: true
#      - name: Login to Heroku Container registry
#        env:
#          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
#        run: heroku container:login
      - name: Create heroku config gile
        run: |
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${{secrets.HEROKU_EMAIL}}
              password ${{secrets.HEROKU_API_KEY}}
          machine git.heroku.com
              login ${{secrets.HEROKU_EMAIL}}
              password ${{secrets.HEROKU_API_KEY}}
          EOF
      - name: Add heroku remote
        run: heroku git:remote --app=${{secrets.HEROKU_APP_NAME}}
      - name: Setup heroku env
        run: heroku config:set DATABASE_URL=${{secrets.DATABASE_URL}}
      - name: push heroku to master
        run: |
          git fetch --unshallow origin
          git push heroku master
